
DEF_OP (OP_NON ,       0,  "non", "NIL")
DEF_OP (OP_SUB_ASSIGN, 5,  "-=",           "S_ASSIGN")
DEF_OP (OP_ADD_ASSIGN, 6,  "+=",           "A_ASSIGN")
DEF_OP (OP_ADD ,       1,  "+",            "ADD")
DEF_OP (OP_SUB ,       2,  "-",            "SUB")
DEF_OP (OP_MUL ,       3,  "*",            "MUL")
DEF_OP (OP_DIV ,       4,  "/",            "DIV")
DEF_OP (OP_IS_EE,      34, "==",           "IS_EE")
DEF_OP (OP_IS_NE,      35, "!=",           "IS_NE")
DEF_OP (OP_PWR ,       7,  "^",            "PWR")
DEF_OP (OP_LBRC,       11, "(",            "\0")
DEF_OP (OP_RBRC,       12, ")",            "\0")
DEF_OP (OP_EOF ,       13, "EOF",          "\0")
DEF_OP (OP_EOS ,       14, "EOS",          "\0")
DEF_OP (OP_ASSGN,      15, "=",            "EQ")
DEF_OP (OP_LQBRC,      16, "[",            "LQBRC")
DEF_OP (OP_RQBRC,      17, "]",            "RQBRC")
DEF_OP (OP_BEGINB,     18, "BEGIN",        "\0")
DEF_OP (OP_ENDB,       19, "END",          "\0")
DEF_OP (OP_IF,         20, "if",           "IF")
DEF_OP (OP_COLON,      21, ":",            "\0")
DEF_OP (OP_ST,         22, "statement",    "ST")
DEF_OP (OP_VAR ,       23, "var",          "VAR")
DEF_OP (OP_WHILE,      24, "while",        "WHILE")
DEF_OP (OP_FUNC,       25, "func",         "FUNC")
DEF_OP (OP_SIN ,       26, "sin",          "SIN")
DEF_OP (OP_COS ,       27, "cos",          "COS")
DEF_OP (OP_RETURN,     28, "return",       "RET")
DEF_OP (OP_COMMA,      29, ",",            "\0")
DEF_OP (OP_CALL,       30, "call",         "CALL")
DEF_OP (OP_INPUT,      31, "input",        "IN")
DEF_OP (OP_PRINT,      32, "print",        "OUT")
DEF_OP (OP_ELSE,       33, "else",         "ELSE")
DEF_OP (OP_IS_GT,      36, ">",            "IS_GT")
DEF_OP (OP_IS_BT,      37, "<",            "IS_BT")
DEF_OP (OP_ELIF,       38, "elif",         "\0")
DEF_OP (OP_SQRT,       39, "sqrt",         "SQRT")
DEF_OP (OP_QUOTE,      40, "\"",           "\0")
DEF_OP (OP_PARAM,      41, "param",        "PARAM")
DEF_OP (OP_STR,        42, "str",          "\0")
DEF_OP (OP_TYPE,       43, "type",         "TYPE")
DEF_OP (OP_VOID,       44, "void",         "VOID")
DEF_OP (OP_TAN,        45, "tan",          "TAN")
